FROM mcr.microsoft.com/dotnet/core-nightly/sdk:3.1.100 as build
WORKDIR /app
COPY ForgeTest/ForgeTest.csproj .
RUN dotnet restore
COPY src src
RUN dotnet build ForgeTest


FROM build as publish
WORKDIR /app
RUN dotnet publish ForgeTest -c Release -o /app -r linux-x64


FROM mcr.microsoft.com/dotnet/core-nightly/runtime:3.1 AS runtime
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV PORT=80
WORKDIR /app
COPY --from=publish /app .
CMD dotnet ForgeTest.dll